# Generated by Django 4.1 on 2022-09-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="instock",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
