# Generated by Django 4.0 on 2022-11-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_izdavastvo_kurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='izdavastvo',
            name='godinaIzdanja',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='izdavastvo',
            name='izdavac',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
