# Generated by Django 4.0 on 2022-11-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_izdavastvo_godinaizdanja_izdavastvo_izdavac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izdavastvo',
            name='description',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
