# Generated by Django 4.0 on 2022-11-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_izdavastvo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
