# Generated by Django 4.0 on 2022-11-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_sr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_zh_hans',
        ),
        migrations.RemoveField(
            model_name='product',
            name='instock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_sr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_zh_hans',
        ),
    ]
