# Generated by Django 4.0 on 2022-11-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
