# Generated by Django 4.0 on 2022-11-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_instock'),
    ]

    operations = [
        migrations.CreateModel(
            name='proizvodnjaPsenicnogBrasnaPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadrzaj', models.CharField(max_length=9999)),
                ('text', models.CharField(max_length=99999)),
            ],
        ),
    ]
