# Generated by Django 4.0 on 2022-11-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_proizvodnjapsenicnogbrasnapdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proizvodnjapsenicnogbrasnapdf',
            name='sadrzaj',
            field=models.TextField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='proizvodnjapsenicnogbrasnapdf',
            name='text',
            field=models.TextField(max_length=99999),
        ),
    ]
