# Generated by Django 4.0 on 2022-11-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_proizvodnjapsenicnogbrasnapdf_sadrzaj_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proizvodnjaPsenicnogBrasnaPdf',
            new_name='proizvodnjaPsenicnogBrasnaInfo',
        ),
    ]
