# Generated by Django 4.0 on 2022-11-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_rename_proizvodnjapsenicnogbrasnapdf_proizvodnjapsenicnogbrasnainfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proizvodnjapsenicnogbrasnainfo',
            name='sadrzaj',
        ),
        migrations.AlterField(
            model_name='proizvodnjapsenicnogbrasnainfo',
            name='text',
            field=models.TextField(max_length=999999),
        ),
    ]
