# Generated by Django 4.0 on 2022-12-27 19:12

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_proizvodnjapsenicnogbrasnainfo_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
